alerts:
  - rule: DEPLOYMENT_FAILED
  - rule: DOMAIN_FAILED
features:
  - buildpack-stack=ubuntu-22
ingress:
  rules:
    - component:
        name: keeper-crud-img
      match:
        path:
          prefix: /
name: oyster-app
region: nyc
services:
  - http_port: 8888
    image:
      deploy_on_push:
        enabled: true
      registry_type: DOCR
      repository: keeper-crud-img
      tag: keeper-server
    instance_count: 1
    instance_size_slug: basic-xs
    name: keeper-crud-img
