alerts:
  - rule: DEPLOYMENT_FAILED
  - rule: DOMAIN_FAILED
features:
  - buildpack-stack=ubuntu-22
ingress:
  rules:
    - component:
        name: keeper-crud-img
      match:
        path:
          prefix: /
name: oyster-app
region: nyc
services:
  - envs:
      - key: KEEPER_DB_PORT
        scope: RUN_AND_BUILD_TIME
        value: ${KEEPER_DB_PORT}
      - key: KEEPER_DB_HOST
        scope: RUN_AND_BUILD_TIME
        value: ${KEEPER_DB_HOST}
      - key: KEEPER_DB_USER
        scope: RUN_AND_BUILD_TIME
        value: ${KEEPER_DB_USER}
      - key: KEEPER_DB_PASSWORD
        scope: RUN_AND_BUILD_TIME
        value: ${KEEPER_DB_PASSWORD}
      - key: KEEPER_DB_NAME
        scope: RUN_AND_BUILD_TIME
        value: ${KEEPER_DB_NAME}
      - key: KEEPER_DB_SSLMODE
        scope: RUN_AND_BUILD_TIME
        value: ${KEEPER_DB_SSLMODE}
      - key: KEEPER_SESSIONS_SECRET
        scope: RUN_AND_BUILD_TIME
        value: ${KEEPER_SESSIONS_SECRET}
    http_port: 8888
    image:
      deploy_on_push:
        enabled: true
      registry_type: DOCR
      repository: keeper-crud-img
      tag: keeper-server
    instance_count: 1
    instance_size_slug: basic-xs
    name: keeper-crud-img
